popularData = [
  "Water",
  "H<sub>2</sub>O",
  "H<sub>2</sub>SO<sub>4</sub>",
  "HCl",
  "H<sub>2</sub>SO<sub>4</sub> + NaOH",
  "Methane",
  "Melatonin",
  "Fe + O<sub>2</sub>",
  "C<sub>2</sub>H<sub>5</sub>OH",
  "Hydrogen peroxide",
  "Sodium chloride",
  "Aspirin",
  "Benzene",
  "Ag + Cl<sub>2</sub>",
];

const colorTypes = {
  "Alkali Metal": "#fd6863",
  "Poor Metal": "#75a1e4",
  "Noble Gas": "#daa2e0",
  "Alkaline Earth Metal": "#feb149",
  Nonmetal: "#a7d04a",
  Lanthanide: "#a0dccc",
  Metalloid: "#5ac0e8",
  Chalcogen: "#89c142",
  Actinide: "#7fb5ae",
  "Transition Metal": "#99c0e5",
  Halogen: "#ff9595",
};

const periodicTable = [
  {
    number: 1,
    symbol: "H",
    name: "Hydrogen",
    mass: 1.008,
    type: "Nonmetal",
    desc: "Hydrogen is the chemical element with the symbol H and atomic number 1. With a standard atomic weight of 1.008, hydrogen is the lightest element in the periodic table. Hydrogen is the most abundant chemical substance in the Universe, constituting roughly 75% of all baryonic mass. Non–remnant stars are mainly composed of hydrogen in the plasma state. The most common isotope of hydrogen, termed protium (name rarely used, symbol 1H), has one proton and no neutrons.",
    summary: {
      symbol: "H",
      name: "Hydrogen",
      latinName: "Hydrogenium",
      chemicalCategory: "Nonmetal",
      atomicWeight: 1.008,
      atomicNumber: 1,
      period: 1,
      group: 1,
      block: "s",
      valence: 1,
      oxidationStates: "-1, +1",
      color: "무색",
      discovery: "1766년 영국",
    },
    radius: {
      atomic: "53 pm",
      covalent: "31 pm",
      vanDerWaals: "120 pm",
      imgSrc: "",
    },
    thermalProperties: {
      phase: "Gas",
      meltingPoint: {
        C: -259.15,
        K: 14,
        F: -434.47,
      },
      boilingPoint: {
        C: -252.88,
        K: 20.27,
        F: -423.19,
      },
      heatOfFusion: "0.558 kJ/mol",
      heatOfVaporisation: "0.452 kJ/mol",
      specificHeat: "14300 J/(kg×K)",
    },
    materialProperties: {
      density: "0.0899 g/l",
      liquidDensity: null,
      molarVolume: 0.01121,
      soundSpeed: "1270 m/s",
      thermalExpansion: null,
      thermalConductivity: "0.1805 W/(m×K)",
      poissonRatio: null,
      crystalStructure: "Hexagonal",
      imgSrc: "",
    },
    hardness: {
      mohs: null,
      vickers: null,
      brinell: null,
    },
    modulus: {
      bulk: null,
      shear: null,
      young: null,
    },
    electromagneticProperties: {
      electricalType: null,
      magneticType: "Diamagnetic",
      resistivity: null,
      conductivity: null,
      curiePoint: null,
      spectralLines: "",
    },
    chemicalProperties: {
      oxidationStates: "-1, +1",
      electronegativity: 2.2,
      electronAffinity: "72.8 kJ/mol",
    },
    ionizationEnergies: {
      first: "1312 kJ/mol",
      second: null,
      third: null,
    },
    abundance: {
      universe: "75%",
      solar: "75%",
      meteorite: "2.4%",
      earthCrust: "0.15%",
      ocean: "11%",
      humanBody: "10%",
    },
    nuclearProperties: {
      radioactivity: "Non–radioactive",
      halfLife: "Stable",
      neutronCrossSection: 0.332,
      neutronMassAbsorption: 0.011,
      stableIsotopes: [1, 2],
      knownIsotopes: [1, 2, 3, 4, 5, 6, 7],
    },
  },
  {
    number: 2,
    symbol: "He",
    name: "Helium",
    mass: 4.003,
    type: "Noble Gas",
    desc: "Helium is a chemical element with the symbol He and atomic number 2. It is a colorless, odorless, tasteless, non–toxic, inert, monatomic gas, the first in the noble gas group in the periodic table. Its boiling point is the lowest among all the elements. Helium is the second lightest and second most abundant element in the observable universe after hydrogen. Large amounts of new helium are being created by nuclear fusion of hydrogen in stars.",
    summary: {
      symbol: "He",
      name: "Helium",
      latinName: "Helium",
      chemicalCategory: "Noble Gas",
      atomicWeight: 4.002602,
      atomicNumber: 2,
      period: 1,
      group: 18,
      block: "s",
      valence: 0,
      oxidationStates: 0,
      color: "무색",
      discovery: "1895년 스웨덴과 영국",
    },
    radius: {
      atomic: "31 pm",
      covalent: "28 pm",
      vanDerWaals: "140 pm",
      imgSrc: "",
    },
    thermalProperties: {
      phase: "Gas",
      meltingPoint: null,
      boilingPoint: {
        C: -268.94,
        K: 4.21,
        F: -452.1,
      },
      heatOfFusion: "f0.02 kJ/mol",
      heatOfVaporisation: "0.083 kJ/mol",
      specificHeat: "5193.1 J/(kg×K)",
    },
    materialProperties: {
      density: "0.1785 g/l",
      liquidDensity: null,
      molarVolume: 0.022424,
      soundSpeed: "970 m/s",
      thermalExpansion: null,
      thermalConductivity: "0.1513 W/(m×K)",
      poissonRatio: null,
      crystalStructure: "Close–packed hexagonal",
      imgSrc: "",
    },
    hardness: {
      mohs: null,
      vickers: null,
      brinell: null,
    },
    modulus: {
      bulk: null,
      shear: null,
      young: null,
    },
    electromagneticProperties: {
      electricalType: null,
      magneticType: "Diamagnetic",
      resistivity: null,
      conductivity: null,
      curiePoint: null,
      spectralLines: "",
    },
    chemicalProperties: {
      oxidationStates: 0,
      electronegativity: null,
      electronAffinity: "0 kJ/mol",
    },
    ionizationEnergies: {
      first: "2372.3 kJ/mol",
      second: "5250.5 kJ/mol",
      third: null,
    },
    abundance: {
      universe: "23%",
      solar: "23%",
      meteorite: null,
      earthCrust: "5.5×10–7 %",
      ocean: "7.2×10–10 %",
      humanBody: null,
    },
    nuclearProperties: {
      radioactivity: "Non–radioactive",
      halfLife: "Stable",
      neutronCrossSection: 0.007,
      neutronMassAbsorption: 0.00001,
      stableIsotopes: [3, 4],
      knownIsotopes: [2, 3, 4, 5, 6, 7, 8, 9, 10],
    },
  },
  {
    number: 3,
    symbol: "Li",
    name: "Lithium",
    mass: 6.94,
    type: "Alkali Metal",
    desc: "Lithium is a chemical element with the symbol Li and atomic number 3. It is a soft, silvery–white alkali metal. Under standard conditions, it is the lightest metal and the lightest solid element. It never occurs freely in nature, but only in compounds, such as pegmatitic minerals, which were once the main source of lithium. Due to its solubility as an ion, it is present in ocean water and is commonly obtained from brines.",
    summary: {
      symbol: "Li",
      name: "Lithium",
      latinName: "Lithium",
      chemicalCategory: "Alkali Metal",
      atomicWeight: 6.94,
      atomicNumber: 3,
      period: 2,
      group: 1,
      block: "s",
      valence: 1,
      oxidationStates: "+1",
      color: "은색",
      discovery: "1817년 스웨덴",
    },
    radius: {
      atomic: "167 pm",
      covalent: "128 pm",
      vanDerWaals: "182 pm",
      imgSrc: "",
    },
    thermalProperties: {
      phase: "Solid",
      meltingPoint: {
        C: 180.53,
        K: 453.68,
        F: 356.95,
      },
      boilingPoint: {
        C: 1342,
        K: 1615.15,
        F: 2447.6,
      },
      heatOfFusion: "3 kJ/mol",
      heatOfVaporisation: "147 kJ/mol",
      specificHeat: "3570 J/(kg×K)",
    },
    materialProperties: {
      density: "0.535 g/cm3",
      liquidDensity: "0.512 g/cm3",
      molarVolume: 0.00001297,
      soundSpeed: "6000 m/s",
      thermalExpansion: "0.000046 K–1",
      thermalConductivity: "85 W/(m×K)",
      poissonRatio: null,
      crystalStructure: "Body–centered cubic",
      imgSrc: "",
    },
    hardness: {
      mohs: 0.6,
      vickers: null,
      brinell: null,
    },
    modulus: {
      bulk: "11 GPa",
      shear: "4.2 GPa",
      young: "4.9 GPa",
    },
    electromagneticProperties: {
      electricalType: "Conductor",
      magneticType: "Paramagnetic",
      resistivity: "9.4×10–8 m×Ω",
      conductivity: "1.1×107 S/m",
      curiePoint: null,
      spectralLines: "",
    },
    chemicalProperties: {
      oxidationStates: +1,
      electronegativity: 0.98,
      electronAffinity: "59.6 kJ/mol",
    },
    ionizationEnergies: {
      first: "520.2 kJ/mol",
      second: "7298.1 kJ/mol",
      third: "11815 kJ/mol",
    },
    abundance: {
      universe: "6×10–7 %",
      solar: "6×10–9 %",
      meteorite: "0.00017 %",
      earthCrust: "0.0017 %",
      ocean: "0.000018 %",
      humanBody: "0.000003 %",
    },
    nuclearProperties: {
      radioactivity: "Non–radioactive",
      halfLife: "Stable",
      neutronCrossSection: 71,
      neutronMassAbsorption: null,
      stableIsotopes: [6, 7],
      knownIsotopes: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    },
  },
  {
    number: 4,
    symbol: "Be",
    name: "Beryllium",
    mass: 9.012,
    type: "Alkaline Earth Metal",
    desc: "Beryllium is a chemical element with the symbol Be and atomic number 4. It is a relatively rare element in the universe, usually occurring as a product of the spallation of larger atomic nuclei that have collided with cosmic rays. Within the cores of stars, beryllium is depleted as it is fused into heavier elements. It is a divalent element which occurs naturally only in combination with other elements in minerals. Notable gemstones which contain beryllium include beryl (aquamarine, emerald) and chrysoberyl. As a free element it is a steel–gray, strong, lightweight and brittle alkaline earth metal.",
    summary: {
      symbol: "Be",
      name: "Beryllium",
      latinName: "Beryllium",
      chemicalCategory: "Alkaline Earth Metal",
      atomicWeight: 9.0121831,
      atomicNumber: 4,
      period: 2,
      group: 2,
      block: "s",
      valence: 2,
      oxidationStates: "+1, +2",
      color: "SlateGray(회색&푸른색)",
      discovery: "1797년 프랑스",
    },
    radius: {
      atomic: "112 pm",
      covalent: "96 pm",
      vanDerWaals: null,
      imgSrc: "",
    },
    thermalProperties: {
      phase: "Solid",
      meltingPoint: {
        C: 1287,
        K: 1560.15,
        F: 2348.6,
      },
      boilingPoint: {
        C: 2470,
        K: 2743.15,
        F: 4478,
      },
      heatOfFusion: "7.95 kJ/mol",
      heatOfVaporisation: "297 kJ/mol",
      specificHeat: "1820 J/(kg×K)",
    },
    materialProperties: {
      density: "1.848 g/cm3",
      liquidDensity: "1.69 g/cm3",
      molarVolume: "4.8767×10–6",
      soundSpeed: "13000 m/s",
      thermalExpansion: "0.0000113 K–1",
      thermalConductivity: "190 W/(m×K)",
      poissonRatio: 0.032,
      crystalStructure: "Close–packed hexagonal",
      imgSrc: "",
    },
    hardness: {
      mohs: 5.5,
      vickers: "1670 MPa",
      brinell: "600 MPa",
    },
    modulus: {
      bulk: "130 GPa",
      shear: "132 GPa",
      young: "287 GPa",
    },
    electromagneticProperties: {
      electricalType: "Conductor",
      magneticType: "Diamagnetic",
      resistivity: "4×10–8 m×Ω",
      conductivity: "2.5×107 S/m",
      curiePoint: null,
      spectralLines: "",
    },
    chemicalProperties: {
      oxidationStates: "+1, +2",
      electronegativity: 1.57,
      electronAffinity: "0 kJ/mol",
    },
    ionizationEnergies: {
      first: "899.5 kJ/mol",
      second: "1757.1 kJ/mol",
      third: "14848.7 kJ/mol",
    },
    abundance: {
      universe: "1×10–7 %",
      solar: "1×10–8 %",
      meteorite: "0.0000029 %",
      earthCrust: "0.00019 %",
      ocean: "6×10–11 %",
      humanBody: "4×10–8 %",
    },
    nuclearProperties: {
      radioactivity: "Non–radioactive",
      halfLife: "Stable",
      neutronCrossSection: 0.0092,
      neutronMassAbsorption: 0.00003,
      stableIsotopes: [9],
      knownIsotopes: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    },
  },
  {
    number: 5,
    symbol: "B",
    name: "Boron",
    mass: 10.81,
    type: "Metalloid",
    desc: "Boron is a chemical element with the symbol B and atomic number 5. Produced entirely by cosmic ray spallation and supernovae and not by stellar nucleosynthesis, it is a low–abundance element in the Solar system and in the Earth's crust. Boron is concentrated on Earth by the water-solubility of its more common naturally occurring compounds, the borate minerals. These are mined industrially as evaporites, such as borax and kernite. The largest known boron deposits are in Turkey, the largest producer of boron minerals.",
    summary: {
      symbol: "Be",
      name: "Boron",
      latinName: "Boron",
      chemicalCategory: "Metalloid",
      atomicWeight: 10.81,
      atomicNumber: 5,
      period: 2,
      group: 13,
      block: "p",
      valence: 3,
      oxidationStates: "−5, −1, +1, +2, +3",
      color: "검정색",
      discovery: "1808년 프랑스와 영국",
    },
    radius: {
      atomic: "87 pm",
      covalent: "85 pm",
      vanDerWaals: null,
      imgSrc: "",
    },
    thermalProperties: {
      phase: "Solid",
      meltingPoint: {
        C: 2075,
        K: 2348.15,
        F: 3767,
      },
      boilingPoint: {
        C: 3999.99,
        K: 4273.14,
        F: 7231.98,
      },
      heatOfFusion: "50 kJ/mol",
      heatOfVaporisation: "507 kJ/mol",
      specificHeat: "1030 J/(kg×K)",
    },
    materialProperties: {
      density: "2.46 g/cm3",
      liquidDensity: "2.08 g/cm3",
      molarVolume: "4.3943×10–6",
      soundSpeed: "16200 m/s",
      thermalExpansion: "6×10–6 K-1",
      thermalConductivity: "27 W/(m×K)",
      poissonRatio: null,
      crystalStructure: "Rhombohedral",
      imgSrc: "",
    },
    hardness: {
      mohs: 9.3,
      vickers: "49000 MPa",
      brinell: null,
    },
    modulus: {
      bulk: "320 GPa",
      shear: null,
      young: null,
    },
    electromagneticProperties: {
      electricalType: "Insulator",
      magneticType: "Diamagnetic",
      resistivity: "10000 m×Ω",
      conductivity: "0.0001 S/m",
      curiePoint: null,
      spectralLines: "",
    },
    chemicalProperties: {
      oxidationStates: "−5, −1, +1, +2, +3",
      electronegativity: 2.04,
      electronAffinity: "26.7 kJ/mol",
    },
    ionizationEnergies: {
      first: "800.6 kJ/mol",
      second: "2427.1 kJ/mol",
      third: "3659.7 kJ/mol",
    },
    abundance: {
      universe: "1×10–7 %",
      solar: "2×10–7 %",
      meteorite: "0.00016 %",
      earthCrust: "0.00086 %",
      ocean: "0.00044 %",
      humanBody: "0.00007 %",
    },
    nuclearProperties: {
      radioactivity: "Non–radioactive",
      halfLife: "Stable",
      neutronCrossSection: 760,
      neutronMassAbsorption: 2.4,
      stableIsotopes: [10, 11],
      knownIsotopes: [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
    },
  },
  {
    number: 6,
    symbol: "C",
    name: "Carbon",
    mass: 12.011,
    type: "Nonmetal",
    desc: "Carbon is a chemical element with the symbol C and atomic number 6. It is nonmetallic and tetravalent—making four electrons available to form covalent chemical bonds. Three isotopes occur naturally, 12C and 13C being stable, while 14C is a radionuclide, decaying with a half–life of about 5,730 years. Carbon is one of the few elements known since antiquity.",
    summary: {
      symbol: "C",
      name: "Carbon",
      latinName: "Carboneum",
      chemicalCategory: "Nonmetal",
      atomicWeight: 12.011,
      atomicNumber: 6,
      period: 2,
      group: 14,
      block: "p",
      valence: 4,
      oxidationStates: "−4, −3, −2, −1, 0, +1, +2, +3, +4",
      color: "검정색",
      discovery: "기원전 3750년",
    },
    radius: {
      atomic: "67 pm",
      covalent: "76 pm",
      vanDerWaals: "170 pm",
      imgSrc: "",
    },
    thermalProperties: {
      phase: "Solid",
      meltingPoint: {
        C: 3550,
        K: 3823.15,
        F: 6422,
      },
      boilingPoint: {
        C: 4026.99,
        K: 4300.14,
        F: 7280.58,
      },
      heatOfFusion: "105 kJ/mol",
      heatOfVaporisation: "715 kJ/mol",
      specificHeat: "710 J/(kg×K)",
    },
    materialProperties: {
      density: "2.26 g/cm3",
      liquidDensity: null,
      molarVolume: "5.3146×10–6",
      soundSpeed: "18350 m/s",
      thermalExpansion: "7.1×10–6 K-1",
      thermalConductivity: "140 W/(m×K)",
      poissonRatio: null,
      crystalStructure: "Hexagonal",
      imgSrc: "",
    },
    hardness: {
      mohs: 0.5,
      vickers: null,
      brinell: null,
    },
    modulus: {
      bulk: "33 GPa",
      shear: null,
      young: null,
    },
    electromagneticProperties: {
      electricalType: "Conductor",
      magneticType: "Diamagnetic",
      resistivity: "0 m×Ω",
      conductivity: "100000 S/m",
      curiePoint: null,
      spectralLines: "",
    },
    chemicalProperties: {
      oxidationStates: "−4, −3, −2, −1, 0, +1, +2, +3, +4",
      electronegativity: 2.55,
      electronAffinity: "153.9 kJ/mol",
    },
    ionizationEnergies: {
      first: "1086.5 kJ/mol",
      second: "2352.6 kJ/mol",
      third: "4620.5 kJ/mol",
    },
    abundance: {
      universe: "0.5 %",
      solar: "0.3 %",
      meteorite: "1.5 %",
      earthCrust: "0.18 %",
      ocean: "0.0028 %",
      humanBody: "23 %",
    },
    nuclearProperties: {
      radioactivity: "Non–radioactive",
      halfLife: "Stable",
      neutronCrossSection: 0.0035,
      neutronMassAbsorption: 0.000015,
      stableIsotopes: [12, 13],
      knownIsotopes: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
    },
  },
  {
    number: 7,
    symbol: "N",
    name: "Nitrogen",
    mass: 14.007,
    type: "Nonmetal",
  },
  {
    number: 8,
    symbol: "O",
    name: "Oxygen",
    mass: 15.999,
    type: "Chalcogen",
  },
  {
    number: 9,
    symbol: "F",
    name: "Fluorine",
    mass: 18.998,
    type: "Halogen",
  },
  {
    number: 10,
    symbol: "Ne",
    name: "Neon",
    mass: 20.18,
    type: "Noble Gas",
  },
  {
    number: 11,
    symbol: "Na",
    name: "Sodium",
    mass: 22.99,
    type: "Alkali Metal",
  },
  {
    number: 12,
    symbol: "Mg",
    name: "Magnesium",
    mass: 24.305,
    type: "Alkaline Earth Metal",
  },
  {
    number: 13,
    symbol: "Al",
    name: "Aluminium",
    mass: 26.982,
    type: "Poor Metal",
  },
  {
    number: 14,
    symbol: "Si",
    name: "Silicon",
    mass: 28.085,
    type: "Metalloid",
  },
  {
    number: 15,
    symbol: "P",
    name: "Phosphorus",
    mass: 30.974,
    type: "Nonmetal",
  },
  {
    number: 16,
    symbol: "S",
    name: "Sulphur",
    mass: 32.06,
    type: "Chalcogen",
  },
  {
    number: 17,
    symbol: "Cl",
    name: "Chlorine",
    mass: 35.45,
    type: "Halogen",
  },
  {
    number: 18,
    symbol: "Ar",
    name: "Argon",
    mass: 39.948,
    type: "Noble Gas",
  },
  {
    number: 19,
    symbol: "K",
    name: "Potassium",
    mass: 39.098,
    type: "Alkali Metal",
  },
  {
    number: 20,
    symbol: "Ca",
    name: "Calcium",
    mass: 40.078,
    type: "Alkaline Earth Metal",
  },
  {
    number: 21,
    symbol: "Sc",
    name: "Scandium",
    mass: 44.956,
    type: "Transition Metal",
  },
  {
    number: 22,
    symbol: "Ti",
    name: "Titanium",
    mass: 47.867,
    type: "Transition Metal",
  },
  {
    number: 23,
    symbol: "V",
    name: "Vanadium",
    mass: 50.942,
    type: "Transition Metal",
  },
  {
    number: 24,
    symbol: "Cr",
    name: "Chromium",
    mass: 51.996,
    type: "Transition Metal",
  },
  {
    number: 25,
    symbol: "Mn",
    name: "Manganese",
    mass: 54.938,
    type: "Transition Metal",
  },
  {
    number: 26,
    symbol: "Fe",
    name: "Iron",
    mass: 55.845,
    type: "Transition Metal",
  },
  {
    number: 27,
    symbol: "Co",
    name: "Cobalt",
    mass: 58.933,
    type: "Transition Metal",
  },
  {
    number: 28,
    symbol: "Ni",
    name: "Nickel",
    mass: 58.693,
    type: "Transition Metal",
  },
  {
    number: 29,
    symbol: "Cu",
    name: "Copper",
    mass: 63.546,
    type: "Transition Metal",
  },
  {
    number: 30,
    symbol: "Zn",
    name: "Zinc",
    mass: 65.38,
    type: "Transition Metal",
  },
  {
    number: 31,
    symbol: "Ga",
    name: "Gallium",
    mass: 69.723,
    type: "Poor Metal",
  },
  {
    number: 32,
    symbol: "Ge",
    name: "Germanium",
    mass: 72.63,
    type: "Metalloid",
  },
  {
    number: 33,
    symbol: "As",
    name: "Arsenic",
    mass: 74.922,
    type: "Metalloid",
  },
  {
    number: 34,
    symbol: "Se",
    name: "Selenium",
    mass: 78.971,
    type: "Chalcogen",
  },
  {
    number: 35,
    symbol: "Br",
    name: "Bromine",
    mass: 79.904,
    type: "Halogen",
  },
  {
    number: 36,
    symbol: "Kr",
    name: "Krypton",
    mass: 83.798,
    type: "Noble Gas",
  },
  {
    number: 37,
    symbol: "Rb",
    name: "Rubidium",
    mass: 85.468,
    type: "Alkali Metal",
  },
  {
    number: 38,
    symbol: "Sr",
    name: "Strontium",
    mass: 87.62,
    type: "Alkaline Earth Metal",
  },
  {
    number: 39,
    symbol: "Y",
    name: "Yttrium",
    mass: 88.906,
    type: "Transition Metal",
  },
  {
    number: 40,
    symbol: "Zr",
    name: "Zirconium",
    mass: 91.224,
    type: "Transition Metal",
  },
  {
    number: 41,
    symbol: "Nb",
    name: "Niobium",
    mass: 92.906,
    type: "Transition Metal",
  },
  {
    number: 42,
    symbol: "Mo",
    name: "Molybdenum",
    mass: 95.95,
    type: "Transition Metal",
  },
  {
    number: 43,
    symbol: "Tc",
    name: "Technetium",
    mass: "[97]",
    type: "Transition Metal",
  },
  {
    number: 44,
    symbol: "Ru",
    name: "Ruthenium",
    mass: 101.07,
    type: "Transition Metal",
  },
  {
    number: 45,
    symbol: "Rh",
    name: "Rhodium",
    mass: 102.906,
    type: "Transition Metal",
  },
  {
    number: 46,
    symbol: "Pd",
    name: "Palladium",
    mass: 106.42,
    type: "Transition Metal",
  },
  {
    number: 47,
    symbol: "Ag",
    name: "Silver",
    mass: 107.868,
    type: "Transition Metal",
  },
  {
    number: 48,
    symbol: "Cd",
    name: "Cadmium",
    mass: 112.414,
    type: "Transition Metal",
  },
  {
    number: 49,
    symbol: "In",
    name: "Indium",
    mass: 114.818,
    type: "Poor Metal",
  },
  {
    number: 50,
    symbol: "Sn",
    name: "Tin",
    mass: 118.71,
    type: "Poor Metal",
  },
  {
    number: 51,
    symbol: "Sb",
    name: "Antimony",
    mass: 121.76,
    type: "Metalloid",
  },
  {
    number: 52,
    symbol: "Te",
    name: "Tellurium",
    mass: 127.6,
    type: "Chalcogen",
  },
  {
    number: 53,
    symbol: "I",
    name: "Iodine",
    mass: 126.904,
    type: "Halogen",
  },
  {
    number: 54,
    symbol: "Xe",
    name: "Xenon",
    mass: 131.293,
    type: "Noble Gas",
  },
  {
    number: 55,
    symbol: "Cs",
    name: "Cesium",
    mass: 132.905,
    type: "Alkali Metal",
  },
  {
    number: 56,
    symbol: "Ba",
    name: "Barium",
    mass: 137.327,
    type: "Alkaline Earth Metal",
  },
  {
    number: 57,
    symbol: "La",
    name: "Lanthanum",
    mass: 138.905,
    type: "Lanthanide",
  },
  {
    number: 72,
    symbol: "Hf",
    name: "Hafnium",
    mass: 178.49,
    type: "Transition Metal",
  },
  {
    number: 73,
    symbol: "Ta",
    name: "Tantalum",
    mass: 180.948,
    type: "Transition Metal",
  },
  {
    number: 74,
    symbol: "W",
    name: "Tungsten",
    mass: 183.84,
    type: "Transition Metal",
  },
  {
    number: 75,
    symbol: "Re",
    name: "Rhenium",
    mass: 186.207,
    type: "Transition Metal",
  },
  {
    number: 76,
    symbol: "Os",
    name: "Osmium",
    mass: 190.23,
    type: "Transition Metal",
  },
  {
    number: 77,
    symbol: "Ir",
    name: "Iridium",
    mass: 192.217,
    type: "Transition Metal",
  },
  {
    number: 78,
    symbol: "Pt",
    name: "Platinum",
    mass: 195.084,
    type: "Transition Metal",
  },
  {
    number: 79,
    symbol: "Au",
    name: "Gold",
    mass: 196.967,
    type: "Transition Metal",
  },
  {
    number: 80,
    symbol: "Hg",
    name: "Mercury",
    mass: 200.592,
    type: "Transition Metal",
  },
  {
    number: 81,
    symbol: "Tl",
    name: "Thallium",
    mass: 204.38,
    type: "Poor Metal",
  },
  {
    number: 82,
    symbol: "Pb",
    name: "Lead",
    mass: 207.2,
    type: "Poor Metal",
  },
  {
    number: 83,
    symbol: "Bi",
    name: "Bismuth",
    mass: 208.98,
    type: "Poor Metal",
  },
  {
    number: 84,
    symbol: "Po",
    name: "Polonium",
    mass: "[209]",
    type: "Chalcogen",
  },
  {
    number: 85,
    symbol: "At",
    name: "Astatine",
    mass: "[210]",
    type: "Halogen",
  },
  {
    number: 86,
    symbol: "Rn",
    name: "Radon",
    mass: "[222]",
    type: "Noble Gas",
  },
  {
    number: 87,
    symbol: "Fr",
    name: "Francium",
    mass: "[223]",
    type: "Alkali Metal",
  },
  {
    number: 88,
    symbol: "Ra",
    name: "Radium",
    mass: "[226]",
    type: "Alkaline Earth Metal",
  },
  {
    number: 89,
    symbol: "Ac",
    name: "Actinium",
    mass: "[227]",
    type: "Actinide",
  },
  {
    number: 104,
    symbol: "Rf",
    name: "Rutherfordium",
    mass: "[267]",
    type: "Transition Metal",
  },
  {
    number: 105,
    symbol: "Db",
    name: "Dubnium",
    mass: "[270]",
    type: "Transition Metal",
  },
  {
    number: 106,
    symbol: "Sg",
    name: "Seaborgium",
    mass: "[269]",
    type: "Transition Metal",
  },
  {
    number: 107,
    symbol: "Bh",
    name: "Bohrium",
    mass: "[270]",
    type: "Transition Metal",
  },
  {
    number: 108,
    symbol: "Hs",
    name: "Hassium",
    mass: "[270]",
    type: "Transition Metal",
  },
  {
    number: 109,
    symbol: "Mt",
    name: "Meitnerium",
    mass: "[278]",
    type: "Transition Metal",
  },
  {
    number: 110,
    symbol: "Ds",
    name: "Darmstadtium",
    mass: "[281]",
    type: "Transition Metal",
  },
  {
    number: 111,
    symbol: "Rg",
    name: "Roentgenium",
    mass: "[281]",
    type: "Transition Metal",
  },
  {
    number: 112,
    symbol: "Cn",
    name: "Copernicium",
    mass: "[285]",
    type: "Transition Metal",
  },
  {
    number: 113,
    symbol: "Nh",
    name: "Nihonium",
    mass: "[286]",
    type: "Poor Metal",
  },
  {
    number: 114,
    symbol: "Fl",
    name: "Flerovium",
    mass: "[289]",
    type: "Poor Metal",
  },
  {
    number: 115,
    symbol: "Mc",
    name: "Moscovium",
    mass: "[289]",
    type: "Poor Metal",
  },
  {
    number: 116,
    symbol: "Lv",
    name: "Livermorium",
    mass: "[293]",
    type: "Poor Metal",
  },
  {
    number: 117,
    symbol: "Ts",
    name: "Tennessine",
    mass: "[293]",
    type: "Halogen",
  },
  {
    number: 118,
    symbol: "Og",
    name: "Oganesson",
    mass: "[294]",
    type: "Noble Gas",
  },
  {
    number: 57,
    symbol: "La",
    name: "Lanthanum",
    mass: 138.905,
    type: "Lanthanide",
  },
  {
    number: 58,
    symbol: "Ce",
    name: "Cerium",
    mass: 140.116,
    type: "Lanthanide",
  },
  {
    number: 59,
    symbol: "Pr",
    name: "Praseodymium",
    mass: 140.908,
    type: "Lanthanide",
  },
  {
    number: 60,
    symbol: "Nd",
    name: "Neodymium",
    mass: 144.242,
    type: "Lanthanide",
  },
  {
    number: 61,
    symbol: "Pm",
    name: "Promethium",
    mass: "[145]",
    type: "Lanthanide",
  },
  {
    number: 62,
    symbol: "Sm",
    name: "Samarium",
    mass: 150.36,
    type: "Lanthanide",
  },
  {
    number: 63,
    symbol: "Eu",
    name: "Europium",
    mass: 151.964,
    type: "Lanthanide",
  },
  {
    number: 64,
    symbol: "Gd",
    name: "Gadolinium",
    mass: 157.25,
    type: "Lanthanide",
  },
  {
    number: 65,
    symbol: "Tb",
    name: "Terbium",
    mass: 158.925,
    type: "Lanthanide",
  },
  {
    number: 66,
    symbol: "Dy",
    name: "Dysprosium",
    mass: 162.5,
    type: "Lanthanide",
  },
  {
    number: 67,
    symbol: "Ho",
    name: "Holmium",
    mass: 164.93,
    type: "Lanthanide",
  },
  {
    number: 68,
    symbol: "Er",
    name: "Erbium",
    mass: 167.259,
    type: "Lanthanide",
  },
  {
    number: 69,
    symbol: "Tm",
    name: "Thulium",
    mass: 168.934,
    type: "Lanthanide",
  },
  {
    number: 70,
    symbol: "Yb",
    name: "Ytterbium",
    mass: 173.045,
    type: "Lanthanide",
  },
  {
    number: 71,
    symbol: "Lu",
    name: "Lutetium",
    mass: 174.967,
    type: "Transition Metal",
  },
  {
    number: 89,
    symbol: "Ac",
    name: "Actinium",
    mass: "[227]",
    type: "Actinide",
  },
  {
    number: 90,
    symbol: "Th",
    name: "Thorium",
    mass: 232.038,
    type: "Actinide",
  },
  {
    number: 91,
    symbol: "Pa",
    name: "Protactinium",
    mass: 231.036,
    type: "Actinide",
  },
  {
    number: 92,
    symbol: "U",
    name: "Uranium",
    mass: 238.029,
    type: "Actinide",
  },
  {
    number: 93,
    symbol: "Np",
    name: "Neptunium",
    mass: "[237]",
    type: "Actinide",
  },
  {
    number: 94,
    symbol: "Pu",
    name: "Plutonium",
    mass: "[244]",
    type: "Actinide",
  },
  {
    number: 95,
    symbol: "Am",
    name: "Americium",
    mass: "[243]",
    type: "Actinide",
  },
  {
    number: 96,
    symbol: "Cm",
    name: "Curium",
    mass: "[247]",
    type: "Actinide",
  },
  {
    number: 97,
    symbol: "Bk",
    name: "Berkelium",
    mass: "[247]",
    type: "Actinide",
  },
  {
    number: 98,
    symbol: "Cf",
    name: "Californium",
    mass: "[251]",
    type: "Actinide",
  },
  {
    number: 99,
    symbol: "Es",
    name: "Einsteinium",
    mass: "[252]",
    type: "Actinide",
  },
  {
    number: 100,
    symbol: "Fm",
    name: "Fermium",
    mass: "[257]",
    type: "Actinide",
  },
  {
    number: 101,
    symbol: "Md",
    name: "Mendelevium",
    mass: "[258]",
    type: "Actinide",
  },
  {
    number: 102,
    symbol: "No",
    name: "Nobelium",
    mass: "[259]",
    type: "Actinide",
  },
  {
    number: 103,
    symbol: "Lr",
    name: "Lawrencium",
    mass: "[262]",
    type: "Transition Metal",
  },
];
