popularData = [
  "Water",
  "H<sub>2</sub>O",
  "H<sub>2</sub>SO<sub>4</sub>",
  "HCl",
  "H<sub>2</sub>SO<sub>4</sub> + NaOH",
  "Methane",
  "Melatonin",
  "Fe + O<sub>2</sub>",
  "C<sub>2</sub>H<sub>5</sub>OH",
  "Hydrogen peroxide",
  "Sodium chloride",
  "Aspirin",
  "Benzene",
  "Ag + Cl<sub>2</sub>",
];

const colorTypes = {
  "Alkali Metal": "#fd6863",
  "Poor Metal": "#75a1e4",
  "Noble Gas": "#daa2e0",
  "Alkaline Earth Metal": "#feb149",
  Nonmetal: "#a7d04a",
  Lanthanide: "#a0dccc",
  Metalloid: "#5ac0e8",
  Chalcogen: "#89c142",
  Actinide: "#7fb5ae",
  "Transition Metal": "#99c0e5",
  Halogen: "#ff9595",
};

const periodicTable = [
  {
    number: 1,
    symbol: "H",
    name: "Hydrogen",
    mass: 1.008,
    type: "Nonmetal",
    desc: "Hydrogen is the chemical element with the symbol H and atomic number 1. With a standard atomic weight of 1.008, hydrogen is the lightest element in the periodic table. Hydrogen is the most abundant chemical substance in the Universe, constituting roughly 75% of all baryonic mass. Non–remnant stars are mainly composed of hydrogen in the plasma state. The most common isotope of hydrogen, termed protium (name rarely used, symbol 1H), has one proton and no neutrons.",
    summary: {
      symbol: "H",
      name: "Hydrogen",
      latinName: "Hydrogenium",
      chemicalCategory: "Nonmetal",
      atomicWeight: 1.008,
      atomicNumber: 1,
      period: 1,
      group: 1,
      block: "s",
      valence: 1,
      oxidationStates: "-1, +1",
      color: "무색",
      discovery: "1766년 영국",
    },
    radius: {
      atomic: "53 pm",
      covalent: "31 pm",
      vanDerWaals: "120 pm",
      imgSrc: "",
    },
    thermalProperties: {
      meltingPoint: {
        C: -259.15,
        K: 14,
        F: -434.47,
      },
      boilingPoint: {
        C: -252.88,
        K: 20.27,
        F: -423.19,
      },
      absoluteZero: "–273,15 °C",
      sunSurface: "5498 °C",
      heatOfFusion: "0.558 kJ/mol",
      heatOfVaporisation: "0.452 kJ/mol",
      specificHeat: "14300 J/(kg×K)",
    },
    materialProperties: {
      density: "0.0899 g/l",
      liquidDensity: null,
      molarVolume: 0.01121,
      soundSpeed: "1270 m/s",
      thermalExpansion: null,
      thermalConductivity: "0.1805 W/(m×K)",
      poissonRatio: null,
      crystalStructure: "Hexagonal",
      imgSrc: "",
    },
    hardness: {
      mohs: null,
      vickers: null,
      brinell: null,
    },
    modulus: {
      bulk: null,
      shear: null,
      young: null,
    },
    electromagneticProperties: {
      electricalType: null,
      magneticType: "Diamagnetic",
      resistivity: null,
      conductivity: null,
      curiePoint: null,
      spectralLines: "",
    },
    chemicalProperties: {
      oxidationStates: "-1, +1",
      electronegativity: 2.2,
      electronAffinity: "72.8 kJ/mol",
    },
    ionizationEnergies: {
      first: "1312 kJ/mol",
      second: null,
      third: null,
    },
    abundance: {
      universe: "75%",
      solar: "75%",
      meteorite: "2.4%",
      earthCrust: "0.15%",
      ocean: "11%",
      humanBody: "10%",
    },
    nuclearProperties: {
      radioactivity: "Non–radioactive",
      halfLife: "Stable",
      neutronCrossSection: 0.332,
      neutronMassAbsorption: 0.011,
      stableIsotopes: [1, 2],
      knownIsotopes: [1, 2, 3, 4, 5, 6, 7],
    },
  },
  {
    number: 2,
    symbol: "He",
    name: "Helium",
    mass: 4.003,
    type: "Noble Gas",
  },
  {
    number: 3,
    symbol: "Li",
    name: "Lithium",
    mass: 6.94,
    type: "Alkali Metal",
  },
  {
    number: 4,
    symbol: "Be",
    name: "Beryllium",
    mass: 9.012,
    type: "Alkaline Earth Metal",
  },
  {
    number: 5,
    symbol: "B",
    name: "Boron",
    mass: 10.81,
    type: "Metalloid",
  },
  {
    number: 6,
    symbol: "C",
    name: "Carbon",
    mass: 12.011,
    type: "Nonmetal",
  },
  {
    number: 7,
    symbol: "N",
    name: "Nitrogen",
    mass: 14.007,
    type: "Nonmetal",
  },
  {
    number: 8,
    symbol: "O",
    name: "Oxygen",
    mass: 15.999,
    type: "Chalcogen",
  },
  {
    number: 9,
    symbol: "F",
    name: "Fluorine",
    mass: 18.998,
    type: "Halogen",
  },
  {
    number: 10,
    symbol: "Ne",
    name: "Neon",
    mass: 20.18,
    type: "Noble Gas",
  },
  {
    number: 11,
    symbol: "Na",
    name: "Sodium",
    mass: 22.99,
    type: "Alkali Metal",
  },
  {
    number: 12,
    symbol: "Mg",
    name: "Magnesium",
    mass: 24.305,
    type: "Alkaline Earth Metal",
  },
  {
    number: 13,
    symbol: "Al",
    name: "Aluminium",
    mass: 26.982,
    type: "Poor Metal",
  },
  {
    number: 14,
    symbol: "Si",
    name: "Silicon",
    mass: 28.085,
    type: "Metalloid",
  },
  {
    number: 15,
    symbol: "P",
    name: "Phosphorus",
    mass: 30.974,
    type: "Nonmetal",
  },
  {
    number: 16,
    symbol: "S",
    name: "Sulphur",
    mass: 32.06,
    type: "Chalcogen",
  },
  {
    number: 17,
    symbol: "Cl",
    name: "Chlorine",
    mass: 35.45,
    type: "Halogen",
  },
  {
    number: 18,
    symbol: "Ar",
    name: "Argon",
    mass: 39.948,
    type: "Noble Gas",
  },
  {
    number: 19,
    symbol: "K",
    name: "Potassium",
    mass: 39.098,
    type: "Alkali Metal",
  },
  {
    number: 20,
    symbol: "Ca",
    name: "Calcium",
    mass: 40.078,
    type: "Alkaline Earth Metal",
  },
  {
    number: 21,
    symbol: "Sc",
    name: "Scandium",
    mass: 44.956,
    type: "Transition Metal",
  },
  {
    number: 22,
    symbol: "Ti",
    name: "Titanium",
    mass: 47.867,
    type: "Transition Metal",
  },
  {
    number: 23,
    symbol: "V",
    name: "Vanadium",
    mass: 50.942,
    type: "Transition Metal",
  },
  {
    number: 24,
    symbol: "Cr",
    name: "Chromium",
    mass: 51.996,
    type: "Transition Metal",
  },
  {
    number: 25,
    symbol: "Mn",
    name: "Manganese",
    mass: 54.938,
    type: "Transition Metal",
  },
  {
    number: 26,
    symbol: "Fe",
    name: "Iron",
    mass: 55.845,
    type: "Transition Metal",
  },
  {
    number: 27,
    symbol: "Co",
    name: "Cobalt",
    mass: 58.933,
    type: "Transition Metal",
  },
  {
    number: 28,
    symbol: "Ni",
    name: "Nickel",
    mass: 58.693,
    type: "Transition Metal",
  },
  {
    number: 29,
    symbol: "Cu",
    name: "Copper",
    mass: 63.546,
    type: "Transition Metal",
  },
  {
    number: 30,
    symbol: "Zn",
    name: "Zinc",
    mass: 65.38,
    type: "Transition Metal",
  },
  {
    number: 31,
    symbol: "Ga",
    name: "Gallium",
    mass: 69.723,
    type: "Poor Metal",
  },
  {
    number: 32,
    symbol: "Ge",
    name: "Germanium",
    mass: 72.63,
    type: "Metalloid",
  },
  {
    number: 33,
    symbol: "As",
    name: "Arsenic",
    mass: 74.922,
    type: "Metalloid",
  },
  {
    number: 34,
    symbol: "Se",
    name: "Selenium",
    mass: 78.971,
    type: "Chalcogen",
  },
  {
    number: 35,
    symbol: "Br",
    name: "Bromine",
    mass: 79.904,
    type: "Halogen",
  },
  {
    number: 36,
    symbol: "Kr",
    name: "Krypton",
    mass: 83.798,
    type: "Noble Gas",
  },
  {
    number: 37,
    symbol: "Rb",
    name: "Rubidium",
    mass: 85.468,
    type: "Alkali Metal",
  },
  {
    number: 38,
    symbol: "Sr",
    name: "Strontium",
    mass: 87.62,
    type: "Alkaline Earth Metal",
  },
  {
    number: 39,
    symbol: "Y",
    name: "Yttrium",
    mass: 88.906,
    type: "Transition Metal",
  },
  {
    number: 40,
    symbol: "Zr",
    name: "Zirconium",
    mass: 91.224,
    type: "Transition Metal",
  },
  {
    number: 41,
    symbol: "Nb",
    name: "Niobium",
    mass: 92.906,
    type: "Transition Metal",
  },
  {
    number: 42,
    symbol: "Mo",
    name: "Molybdenum",
    mass: 95.95,
    type: "Transition Metal",
  },
  {
    number: 43,
    symbol: "Tc",
    name: "Technetium",
    mass: "[97]",
    type: "Transition Metal",
  },
  {
    number: 44,
    symbol: "Ru",
    name: "Ruthenium",
    mass: 101.07,
    type: "Transition Metal",
  },
  {
    number: 45,
    symbol: "Rh",
    name: "Rhodium",
    mass: 102.906,
    type: "Transition Metal",
  },
  {
    number: 46,
    symbol: "Pd",
    name: "Palladium",
    mass: 106.42,
    type: "Transition Metal",
  },
  {
    number: 47,
    symbol: "Ag",
    name: "Silver",
    mass: 107.868,
    type: "Transition Metal",
  },
  {
    number: 48,
    symbol: "Cd",
    name: "Cadmium",
    mass: 112.414,
    type: "Transition Metal",
  },
  {
    number: 49,
    symbol: "In",
    name: "Indium",
    mass: 114.818,
    type: "Poor Metal",
  },
  {
    number: 50,
    symbol: "Sn",
    name: "Tin",
    mass: 118.71,
    type: "Poor Metal",
  },
  {
    number: 51,
    symbol: "Sb",
    name: "Antimony",
    mass: 121.76,
    type: "Metalloid",
  },
  {
    number: 52,
    symbol: "Te",
    name: "Tellurium",
    mass: 127.6,
    type: "Chalcogen",
  },
  {
    number: 53,
    symbol: "I",
    name: "Iodine",
    mass: 126.904,
    type: "Halogen",
  },
  {
    number: 54,
    symbol: "Xe",
    name: "Xenon",
    mass: 131.293,
    type: "Noble Gas",
  },
  {
    number: 55,
    symbol: "Cs",
    name: "Cesium",
    mass: 132.905,
    type: "Alkali Metal",
  },
  {
    number: 56,
    symbol: "Ba",
    name: "Barium",
    mass: 137.327,
    type: "Alkaline Earth Metal",
  },
  {
    number: 57,
    symbol: "La",
    name: "Lanthanum",
    mass: 138.905,
    type: "Lanthanide",
  },
  {
    number: 72,
    symbol: "Hf",
    name: "Hafnium",
    mass: 178.49,
    type: "Transition Metal",
  },
  {
    number: 73,
    symbol: "Ta",
    name: "Tantalum",
    mass: 180.948,
    type: "Transition Metal",
  },
  {
    number: 74,
    symbol: "W",
    name: "Tungsten",
    mass: 183.84,
    type: "Transition Metal",
  },
  {
    number: 75,
    symbol: "Re",
    name: "Rhenium",
    mass: 186.207,
    type: "Transition Metal",
  },
  {
    number: 76,
    symbol: "Os",
    name: "Osmium",
    mass: 190.23,
    type: "Transition Metal",
  },
  {
    number: 77,
    symbol: "Ir",
    name: "Iridium",
    mass: 192.217,
    type: "Transition Metal",
  },
  {
    number: 78,
    symbol: "Pt",
    name: "Platinum",
    mass: 195.084,
    type: "Transition Metal",
  },
  {
    number: 79,
    symbol: "Au",
    name: "Gold",
    mass: 196.967,
    type: "Transition Metal",
  },
  {
    number: 80,
    symbol: "Hg",
    name: "Mercury",
    mass: 200.592,
    type: "Transition Metal",
  },
  {
    number: 81,
    symbol: "Tl",
    name: "Thallium",
    mass: 204.38,
    type: "Poor Metal",
  },
  {
    number: 82,
    symbol: "Pb",
    name: "Lead",
    mass: 207.2,
    type: "Poor Metal",
  },
  {
    number: 83,
    symbol: "Bi",
    name: "Bismuth",
    mass: 208.98,
    type: "Poor Metal",
  },
  {
    number: 84,
    symbol: "Po",
    name: "Polonium",
    mass: "[209]",
    type: "Chalcogen",
  },
  {
    number: 85,
    symbol: "At",
    name: "Astatine",
    mass: "[210]",
    type: "Halogen",
  },
  {
    number: 86,
    symbol: "Rn",
    name: "Radon",
    mass: "[222]",
    type: "Noble Gas",
  },
  {
    number: 87,
    symbol: "Fr",
    name: "Francium",
    mass: "[223]",
    type: "Alkali Metal",
  },
  {
    number: 88,
    symbol: "Ra",
    name: "Radium",
    mass: "[226]",
    type: "Alkaline Earth Metal",
  },
  {
    number: 89,
    symbol: "Ac",
    name: "Actinium",
    mass: "[227]",
    type: "Actinide",
  },
  {
    number: 104,
    symbol: "Rf",
    name: "Rutherfordium",
    mass: "[267]",
    type: "Transition Metal",
  },
  {
    number: 105,
    symbol: "Db",
    name: "Dubnium",
    mass: "[270]",
    type: "Transition Metal",
  },
  {
    number: 106,
    symbol: "Sg",
    name: "Seaborgium",
    mass: "[269]",
    type: "Transition Metal",
  },
  {
    number: 107,
    symbol: "Bh",
    name: "Bohrium",
    mass: "[270]",
    type: "Transition Metal",
  },
  {
    number: 108,
    symbol: "Hs",
    name: "Hassium",
    mass: "[270]",
    type: "Transition Metal",
  },
  {
    number: 109,
    symbol: "Mt",
    name: "Meitnerium",
    mass: "[278]",
    type: "Transition Metal",
  },
  {
    number: 110,
    symbol: "Ds",
    name: "Darmstadtium",
    mass: "[281]",
    type: "Transition Metal",
  },
  {
    number: 111,
    symbol: "Rg",
    name: "Roentgenium",
    mass: "[281]",
    type: "Transition Metal",
  },
  {
    number: 112,
    symbol: "Cn",
    name: "Copernicium",
    mass: "[285]",
    type: "Transition Metal",
  },
  {
    number: 113,
    symbol: "Nh",
    name: "Nihonium",
    mass: "[286]",
    type: "Poor Metal",
  },
  {
    number: 114,
    symbol: "Fl",
    name: "Flerovium",
    mass: "[289]",
    type: "Poor Metal",
  },
  {
    number: 115,
    symbol: "Mc",
    name: "Moscovium",
    mass: "[289]",
    type: "Poor Metal",
  },
  {
    number: 116,
    symbol: "Lv",
    name: "Livermorium",
    mass: "[293]",
    type: "Poor Metal",
  },
  {
    number: 117,
    symbol: "Ts",
    name: "Tennessine",
    mass: "[293]",
    type: "Halogen",
  },
  {
    number: 118,
    symbol: "Og",
    name: "Oganesson",
    mass: "[294]",
    type: "Noble Gas",
  },
  {
    number: 57,
    symbol: "La",
    name: "Lanthanum",
    mass: 138.905,
    type: "Lanthanide",
  },
  {
    number: 58,
    symbol: "Ce",
    name: "Cerium",
    mass: 140.116,
    type: "Lanthanide",
  },
  {
    number: 59,
    symbol: "Pr",
    name: "Praseodymium",
    mass: 140.908,
    type: "Lanthanide",
  },
  {
    number: 60,
    symbol: "Nd",
    name: "Neodymium",
    mass: 144.242,
    type: "Lanthanide",
  },
  {
    number: 61,
    symbol: "Pm",
    name: "Promethium",
    mass: "[145]",
    type: "Lanthanide",
  },
  {
    number: 62,
    symbol: "Sm",
    name: "Samarium",
    mass: 150.36,
    type: "Lanthanide",
  },
  {
    number: 63,
    symbol: "Eu",
    name: "Europium",
    mass: 151.964,
    type: "Lanthanide",
  },
  {
    number: 64,
    symbol: "Gd",
    name: "Gadolinium",
    mass: 157.25,
    type: "Lanthanide",
  },
  {
    number: 65,
    symbol: "Tb",
    name: "Terbium",
    mass: 158.925,
    type: "Lanthanide",
  },
  {
    number: 66,
    symbol: "Dy",
    name: "Dysprosium",
    mass: 162.5,
    type: "Lanthanide",
  },
  {
    number: 67,
    symbol: "Ho",
    name: "Holmium",
    mass: 164.93,
    type: "Lanthanide",
  },
  {
    number: 68,
    symbol: "Er",
    name: "Erbium",
    mass: 167.259,
    type: "Lanthanide",
  },
  {
    number: 69,
    symbol: "Tm",
    name: "Thulium",
    mass: 168.934,
    type: "Lanthanide",
  },
  {
    number: 70,
    symbol: "Yb",
    name: "Ytterbium",
    mass: 173.045,
    type: "Lanthanide",
  },
  {
    number: 71,
    symbol: "Lu",
    name: "Lutetium",
    mass: 174.967,
    type: "Transition Metal",
  },
  {
    number: 89,
    symbol: "Ac",
    name: "Actinium",
    mass: "[227]",
    type: "Actinide",
  },
  {
    number: 90,
    symbol: "Th",
    name: "Thorium",
    mass: 232.038,
    type: "Actinide",
  },
  {
    number: 91,
    symbol: "Pa",
    name: "Protactinium",
    mass: 231.036,
    type: "Actinide",
  },
  {
    number: 92,
    symbol: "U",
    name: "Uranium",
    mass: 238.029,
    type: "Actinide",
  },
  {
    number: 93,
    symbol: "Np",
    name: "Neptunium",
    mass: "[237]",
    type: "Actinide",
  },
  {
    number: 94,
    symbol: "Pu",
    name: "Plutonium",
    mass: "[244]",
    type: "Actinide",
  },
  {
    number: 95,
    symbol: "Am",
    name: "Americium",
    mass: "[243]",
    type: "Actinide",
  },
  {
    number: 96,
    symbol: "Cm",
    name: "Curium",
    mass: "[247]",
    type: "Actinide",
  },
  {
    number: 97,
    symbol: "Bk",
    name: "Berkelium",
    mass: "[247]",
    type: "Actinide",
  },
  {
    number: 98,
    symbol: "Cf",
    name: "Californium",
    mass: "[251]",
    type: "Actinide",
  },
  {
    number: 99,
    symbol: "Es",
    name: "Einsteinium",
    mass: "[252]",
    type: "Actinide",
  },
  {
    number: 100,
    symbol: "Fm",
    name: "Fermium",
    mass: "[257]",
    type: "Actinide",
  },
  {
    number: 101,
    symbol: "Md",
    name: "Mendelevium",
    mass: "[258]",
    type: "Actinide",
  },
  {
    number: 102,
    symbol: "No",
    name: "Nobelium",
    mass: "[259]",
    type: "Actinide",
  },
  {
    number: 103,
    symbol: "Lr",
    name: "Lawrencium",
    mass: "[262]",
    type: "Transition Metal",
  },
];
